### ISSUE TITLE
TypeError occurs when in View Appointments list

### ISSUE THREAD

**Issue by dkomarov** [567WebSystems/project-3-beta#6]
When loading the view appointments page, this is what the console is showing:

<img width="1197" alt="typeError" src="https://user-images.githubusercontent.com/21226482/79266216-d5f64900-7e5c-11ea-9b15-69726e904916.png">

This problem goes away when on the appointment and update forms because of the submit input field. Post your suggestions or fixes in the comments below. Thanks!

**Comment by dhirajj14** [comment]
For this we can say this is not the error but the accepted error which occurs in case of it can't find the element on the web page. For our application we are using only one javascript script file for all the views, therefore when on the view-appointment page it can't find the submit button. Hence it gives this error but this can be ignored as we are using on script file
